AppBundle\Entity\Product:
    exclusion_policy: none
    properties:
        product_id:
            groups: ['product']
        description:
            groups: ['product']
        is_fixed:
            groups: ['product']
        price:
            groups: ['product']
        axe:
            groups: ['product']