AppBundle\Entity\Product:
    exclusion_policy: none
    properties:
        product_id:
            groups: ['product', 'click']
        description:
            groups: ['product', 'click']
        is_fixed:
            groups: ['product', 'click']
        price:
            groups: ['product', 'click']
        axe:
            groups: ['product', 'click']